# -*- coding: utf-8 -*-
"""Copa_vino.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tOsWLZfTgZW-XVEYKU-1o2c6cNCd7OBD
"""

#Librerias de apoyo
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import math

#Multiplicación de matrices
def mul(matriz1,matriz2):

    r1=len(matriz1)
    c1=len(matriz1[0])
    c2=len(matriz2[0])

    resultado=list()
    for i in range(r1):
        resultado.append(list())
        for j in range(c2):
            resul = 0
            for k in range(c1):
                resul+=matriz1[i][k]*matriz2[k][j]
            resultado[i].append(resul)

    return resultado


#Rotación alrededor de x
def rotX(punto, angx):
    Rx = [[1,0,0,0],
      [0,math.cos(angx*math.pi/180),-math.sin(angx*math.pi/180),0],
      [0,math.sin(angx*math.pi/180),math.cos(angx*math.pi/180),0],
      [0,0,0,1]]

    return mul(Rx,punto)

#Rotación alrededor de y
def rotY(punto, angy):
    Ry = [[math.cos(angy*math.pi/180),0,math.sin(angy*math.pi/180),0],
      [0,1,0,0],
      [-math.sin(angy*math.pi/180),0,math.cos(angy*math.pi/180),0],
      [0,0,0,1]]

    return mul(Ry,punto)

#Rotación alrededor de z
def rotZ(punto, angz):
    Rz = [[math.cos(angz*math.pi/180),-math.sin(angz*math.pi/180),0,0],
      [math.sin(angz*math.pi/180),math.cos(angz*math.pi/180),0,0],
      [0,0,1,0],
      [0,0,0,1]]

    return mul(Rz,punto)

#Traslación
def tras(punto, x, y, z):
    T = [[1,0,0,x],
      [0,1,0,y],
      [0,0,1,z],
      [0,0,0,1]]

    return mul(T,punto)

#Graficar
def graficar(step,punto,axe):
    ang=0

    listX=list()
    listY=list()
    listZ=list()

    for i in range(step+1):

        ang = i*360/step

        res = rotZ(punto,ang)

        listX.append(res[0][0])
        listY.append(res[1][0])
        listZ.append(res[2][0])

    axe.plot(listX,listY,listZ)

#gráfica
st=50

fig = plt.figure()
#ax = fig.gca(projection='3d')  #deprecado
ax = fig.add_subplot(projection='3d')

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

ax.autoscale(enable=True)


Pini=[[0],[0],[0],[1]]

#base con traslaciones
#[[3],[0],[0],[1]]
#1- (x) diametro, 2- (y) se deja igual en 0, 3- (z) eje z
PB=tras(Pini,5,0,0)
graficar(st,PB,ax)

PB2= tras(Pini,4.5,0,0.3)
graficar(st,PB2,ax)

PB3= tras(Pini,4,0,0.6)
graficar(st,PB3,ax)

PB4= tras(Pini,3.5,0,0.9)
graficar(st,PB4,ax)

PB5= tras(Pini,3,0,0.9)
graficar(st,PB5,ax)

PB6= tras(Pini,2.5,0,0.9)
graficar(st,PB6,ax)

PB7= tras(Pini,2,0,0.9)
graficar(st,PB7,ax)

PB8= tras(Pini,1.5,0,0.9)
graficar(st,PB8,ax)

PB10= tras(Pini,1,0,1.2)
graficar(st,PB10,ax)

#pedestal

#PP= [[2],[0],[1],[1]]
#graficar(st,PP,ax)
#1-(x)diametro, 2-(y)Ancho(Siempre se deja en 0) , 3-(z)ejez, 4- Se deja en 1
PP= [[1],[0],[1.2],[1]]
graficar(st,PP,ax)

PP2= [[1],[0],[1.8],[1]]
graficar(st,PP2,ax)

PP3= [[1],[0],[2.4],[1]]
graficar(st,PP3,ax)

PP4= [[1],[0],[3],[1]]
graficar(st,PP4,ax)

PP5= [[1],[0],[3.6],[1]]
graficar(st,PP5,ax)

PP6= [[1],[0],[4.2],[1]]
graficar(st,PP6,ax)

PP7= [[1],[0],[4.8],[1]]
graficar(st,PP7,ax)

PP8= [[1],[0],[5.4],[1]]
graficar(st,PP8,ax)

PP9= [[1],[0],[6],[1]]
graficar(st,PP9,ax)

PP10= [[1],[0],[6.6],[1]]
graficar(st,PP10,ax)

PP11= [[1],[0],[7.2],[1]]
graficar(st,PP11,ax)

PP12= [[1],[0],[7.7],[1]]
graficar(st,PP12,ax)

PP13= [[1],[0],[8.2],[1]]
graficar(st,PP13,ax)



#copa


PC=[[1.782],[0],[8.8],[1]] #Principio
graficar(st,PC,ax)

PC2=[[2.564],[0],[9.4],[1]]
graficar(st,PC2,ax)

PC3=[[3.346],[0],[10],[1]]
graficar(st,PC3,ax)

PC4=[[4.128],[0],[10.6],[1]]
graficar(st,PC4,ax)

PC5=[[4.91],[0],[11.2],[1]]
graficar(st,PC5,ax)

PC6=[[5.692],[0],[11.8],[1]]
graficar(st,PC6,ax)

PC7=[[6.474],[0],[12.4],[1]]
graficar(st,PC7,ax)

PC8=[[7.256],[0],[13],[1]]
graficar(st,PC8,ax)

PC9=[[8.038],[0],[13.6],[1]]
graficar(st,PC9,ax)

PC10=[[8.82],[0],[14.2],[1]] #La mitad
graficar(st,PC10,ax)

PC11=[[8.58],[0],[14.8],[1]]
graficar(st,PC11,ax)

PC12=[[8.34],[0],[15.4],[1]]
graficar(st,PC12,ax)

PC13=[[8.1],[0],[16],[1]]
graficar(st,PC13,ax)

PC14=[[7.86],[0],[16.6],[1]]
graficar(st,PC14,ax)

PC15=[[7.62],[0],[17.2],[1]]
graficar(st,PC15,ax)

PC16=[[7.38],[0],[17.8],[1]]
graficar(st,PC16,ax)

PC17=[[7.14],[0],[18.4],[1]]
graficar(st,PC17,ax)

PC18=[[6.9],[0],[19],[1]]
graficar(st,PC18,ax)

PC19=[[6.66],[0],[19.6],[1]]
graficar(st,PC19,ax)

PC20=[[6.42],[0],[20.2],[1]]
graficar(st,PC20,ax)

#Tapadera

PC21=[[6],[0],[20.2],[1]]
graficar(st,PC21,ax)

PC22=[[5.5],[0],[20.2],[1]]
graficar(st,PC22,ax)

PC23=[[5],[0],[20.2],[1]]
graficar(st,PC23,ax)

PC24=[[4.5],[0],[20.2],[1]]
graficar(st,PC24,ax)

PC25=[[4],[0],[20.2],[1]]
graficar(st,PC25,ax)

PC26=[[3.5],[0],[20.2],[1]]
graficar(st,PC26,ax)

PC27=[[3],[0],[20.2],[1]]
graficar(st,PC27,ax)

PC28=[[2.5],[0],[20.2],[1]]
graficar(st,PC28,ax)

PC29=[[2],[0],[20.2],[1]]
graficar(st,PC29,ax)

PC30=[[1.5],[0],[20.2],[1]]
graficar(st,PC30,ax)

PC31=[[1],[0],[20.2],[1]]
graficar(st,PC31,ax)


#Popote

PC32=[[1],[0],[21.2],[1]]
graficar(st,PC32,ax)

PC33=[[1],[0],[22.2],[1]]
graficar(st,PC33,ax)

PC34=[[1],[0],[23.2],[1]]
graficar(st,PC34,ax)

PC35=[[1],[0],[24.2],[1]]
graficar(st,PC35,ax)

PC36=[[1],[0],[25.2],[1]]
graficar(st,PC36,ax)

PC37=[[1],[0],[26.2],[1]]
graficar(st,PC37,ax)

PC38=[[1],[0],[27.2],[1]]
graficar(st,PC38,ax)

PC39=[[1],[0],[28.2],[1]]
graficar(st,PC39,ax)



plt.show()